services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    image: paysnap-backend:local
    container_name: paysnap-backend
    environment:
      - PORT=8000
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    image: paysnap-frontend:local
    container_name: paysnap-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
